; Auto-generated. Do not edit!


(cl:in-package motion_msgs-msg)


;//! \htmlinclude MoveRobotFeedback.msg.html

(cl:defclass <MoveRobotFeedback> (roslisp-msg-protocol:ros-message)
  ((location
    :reader location
    :initarg :location
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass MoveRobotFeedback (<MoveRobotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveRobotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveRobotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_msgs-msg:<MoveRobotFeedback> is deprecated: use motion_msgs-msg:MoveRobotFeedback instead.")))

(cl:ensure-generic-function 'location-val :lambda-list '(m))
(cl:defmethod location-val ((m <MoveRobotFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_msgs-msg:location-val is deprecated.  Use motion_msgs-msg:location instead.")
  (location m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveRobotFeedback>) ostream)
  "Serializes a message object of type '<MoveRobotFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'location) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveRobotFeedback>) istream)
  "Deserializes a message object of type '<MoveRobotFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'location) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveRobotFeedback>)))
  "Returns string type for a message object of type '<MoveRobotFeedback>"
  "motion_msgs/MoveRobotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveRobotFeedback)))
  "Returns string type for a message object of type 'MoveRobotFeedback"
  "motion_msgs/MoveRobotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveRobotFeedback>)))
  "Returns md5sum for a message object of type '<MoveRobotFeedback>"
  "5e8ac99e71b788e7cf0b5b68b9c6b3f8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveRobotFeedback)))
  "Returns md5sum for a message object of type 'MoveRobotFeedback"
  "5e8ac99e71b788e7cf0b5b68b9c6b3f8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveRobotFeedback>)))
  "Returns full string definition for message of type '<MoveRobotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/PoseStamped location~%~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveRobotFeedback)))
  "Returns full string definition for message of type 'MoveRobotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/PoseStamped location~%~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveRobotFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'location))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveRobotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveRobotFeedback
    (cl:cons ':location (location msg))
))
